import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/partials/Navbar/Navbar";
import Footer from "@/components/partials/Footer/Footer";
import { getUserFromCookie } from "@/lib/getUserFromCookie/getUserFromCookie";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Kaçak Film Cenneti",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await getUserFromCookie()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Navbar data={data} />

        <main className="flex-1">
          {children}
        </main>

        <Footer />
      </body>
    </html>

  );
}
